In [1]:
# TASK: Import the following libraries that we will use: nibabel, matplotlib, numpy
import matplotlib.pyplot as plt
import numpy as np
import nibabel as nib
import os
import glob
import shutil
from os import listdir
from os import walk
from os.path import join

%matplotlib inline

In [2]:
def getFileNames(mypath):
    f = []
    for (dirpath, dirnames, filenames) in walk(mypath):        
        filenames = [ f for f in filenames if f.endswith("nii.gz")]        
        f.extend(filenames)
    return f


LABELS_DIR = "..\data\TrainingSet\labels"

labels_list = getFileNames(LABELS_DIR)

In [4]:
def get_file_path(directory,filename):
    path = os.path.join(directory, filename)    
    if os.path.exists(path):
        return path
    return None

In [6]:
label = nib.load(get_file_path(LABELS_DIR,labels_list[0])).get_fdata()

In [7]:
print(label)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [11]:
type(label[0][0][0])

numpy.float64

In [13]:
import sys
print(sys.getsizeof(label))

499928


In [14]:
print(sys.getsizeof(label.astype(int)))

250028


In [15]:
label.shape

(35, 51, 35)